### ISSUE TITLE
Problème avec le mode préréglage

### ISSUE THREAD

**Issue by grigaux** [maheus/fumis_integration#13]
Bonjour @maheus ,

J'ai un soucis avec le mode préréglage. J'ai malencontreusement désactivé le mode ECO en cliquant sur le bouton et impossible de le rétablir. Il revient en mode "aucun" après quelques secondes lorsque je valide " ECO". Je ne vois pas d'erreur dans le fichier journal.
Comment rétablir le mode ECO sur mon poêle car sinon il ne s'arrête plus automatiquement lorsque la température est atteinte.

Merci pour votre aide.
Cordialement,

[
![Capture d’écran 2023-12-11 135045](https://github.com/maheus/fumis_integration/assets/33656927/3c935fdd-902a-415e-8617-fa765638520b)

**Comment by grigaux** [comment]
Bonjour,

J'ai essayé de changer ce paramètre avec postman . Est-ce qu'il suffit de mettre:

"ecoMode": {
            "ecoModeSetType": 0,
            "ecoModeEnable": 1
}

Mais le mode ecoModeEnable repasse automatiquement à 0. SI je mets la valeur à -1 il la garde bien mais je ne sais pas quelle valeur renseignée.
Merci

**Comment by maheus** [comment]
bonjour,

bizarre si il revient en mode aucun, c'est l'api qui le rechange

**Comment by maheus** [comment]
vous n'avez pas d'appli moobile ou directement depuis votre poêle l'option ?

**Comment by grigaux** [comment]
Bonjour,
Cette gestion du mode ECO n'est pas disponible depuis l'appli ou l'afficheur du poêle. C'est ce qui m'embête. Quelle devrait être les valeurs de ecoModeSetType et ecoModeEnable lorsque le mode est activé ?
Merci

**Comment by maheus** [comment]
quel est le modèle et la marque de votre poële svp ? Si l'appli et l'afficheur ne le gère pas je ne suis pas certain que votre poële le gère également.
Pour `ecoModeEnable` il est soit à 1 ou 0 , pour `ecoModeSetType` cela dépend de votre poële donc l'intégration n'y touche pas. Je vous conseillerais via Postman de tester plusieurs valeurs pour voir si vous obtenez celle qui vous convient.

**Comment by grigaux** [comment]
C'est un HETA green 200. 
Si je mets ecoModeEnable à 0 ou -1 ou -2 par exemple il le garde. tout le reste il l'ignore.

**Comment by maheus** [comment]
oui je pense que dès que vous mettez 1 ou plus à `ecoModeEnable` il faut que `ecoModeSetType` est une valeur également

**Comment by grigaux** [comment]
Donc il faut que je trouve la valeur par défaut du paramètre ecoModeSetType 

Je crois que je vais devoir faire reflasher la carte ...

**Comment by maheus** [comment]
à mon avis la valeur doit pas être compliqué à touver , je dirais entre 1 et 3 grand max

**Comment by grigaux** [comment]
j'ai essayé jusqu'à 10 pour ecoModeSetType mais ecoModeEnable n'est pas conservé

**Comment by maheus** [comment]
:( , vous avez du flasher la carte pour ajouter des fonctionnalités ?  il faut peut etre voir si on a accès au code source

**Comment by grigaux** [comment]
Non c'est la carte d'origine FUMIS. mais si je ne peux pas retrouver le mode de fonctionnement d'origine je vais devoir demander à mon installateur de remettre les paramètres d'usine.

**Comment by maheus** [comment]
j'ai trouvé ça sur le net : https://www.dropbox.com/s/26iu43r6hav51p1/Fumis_Soft.zip?dl=0
la doc est pas mal https://www.dropbox.com/s/26iu43r6hav51p1/Fumis_Soft.zip?dl=0&file_subpath=%2FFumis_Advanced+Functions.pdf

**Comment by grigaux** [comment]
Oui je l'avais récupéré mais il va me manquer le boitier pour brancher sur pc. j'ai essayer avec un câble  usb-rj11 mais cela ne fonctionne pas. je crois que fumis utilise un boitier spécial.

**Comment by maheus** [comment]
autre solution "bourrine" mais qui devrait fonctionner, un petit script qui va tester les valeurs de 1 à 1000 et à chaque occurence il test avec un GET si la valeur est la bonne si elle est ok alors il se stoppe

**Comment by grigaux** [comment]
J'ai avancé un peu. j'ai relu la doc et activé le paramètre 53 à 1 (il était à 0 et cela désactive l'ecomode) .
Sur l'afficheur de l'application officielle j'ai la mention " en attente mode ECO" comme avant. Je verrai si le poêle se déclenche
 
Le fait de basculer le PRESET et forcer le **ecoModeEnable**  à 0 a du changer d'autres paramètres . par contre ecoModeEnable reste à 0. 
Pour l'instant j'ai touché au PAR 50 et 53.
Peut être signaler que ce paramètre de PRESET peut avoir des incidences et des retours en arrière pas simple suivant la marque et modèle des poêles.

**Comment by maheus** [comment]
pas de soucis mais j'aimerais d'abord que vous reproduisez le soucis car en l'immédiat je ne comprend pas comment en changeant le mode eco cela à pu agir sur un autre paramètre

**Comment by maheus** [comment]
pour info voici les miens
 ```   
 "ecoMode": {
      "ecoModeSetType": 1,
      "ecoModeEnable": 1
    },
```

ainsi que le paramètre 53
```
        {
          "id": 53,
          "value": 253
        },
```

**Comment by grigaux** [comment]
Vous avez le même poêle ?

J'ai pu reproduire le problème, dès que je clique sur préréglage "aucun", les ID 50 et 53 repassent à 0. Je les repasse à 1 pour réactiver le mode eco et configuré la température delta d'arrêt et de reprise. Je parle des ID situés dans
"diagnostic / parameters" Je n'ai pas touché à ceux situés dans variable.

En enlevant vos informations personnelles, pourriez vous me fournir svp le contenu de votre fichier status afin de comparer?
Merci d'avance.

**Comment by maheus** [comment]
non malheuresement je n'ai pas le même poële ce qui fait que je n'ai jamais eu ce comportement. (ni personne avant vous pour le moment)
```
        {
          "id": 50,
          "value": 20210211
        },
        {
          "id": 53,
          "value": 253
        },
```
je vais indiquer dans le readme ce comportement, pour le moins surprenant.

**Comment by grigaux** [comment]
Les ID n'ont pas l'air commun. l'ID 50 correspond plus à une date pour vous. Ca doit dépendre du type de carte surement.

**Comment by maheus** [comment]
il y a des chances. 
Pouvez vous me fournir le POST que vous avez fait pour remettre les paramètres 1 sur les deux id 50 et 53 svp

**Comment by grigaux** [comment]
Voici le code:
```
{
     "apiVersion": "1.3",
     "unit": {
         "id": "xxxx",
         "pin": "xxxxx",
         "type": 0,
         "version": "2.4.0"      
     },
     "controller": {
         "ecoMode": 
             {
                "ecoModeSetType": 1,
                "ecoModeEnable": 1
                
             },
         "diagnostic": {
            "parameters": [
                {
                    "id": 53,
                    "value": 1
                },
                {
                    "id": 50,
                    "value": 1
                }
                
            ]}
         
     }
 }
```

**Comment by grigaux** [comment]
Par contre, maintenant il faut que je trouve les bonnes valeurs pour ces ID car cela ne correspond pas exactement à la doc. Le poêle se met en marche à partir de la valeur demandée et non plus à la valeur souhaitée -1. A priori la valuer serait en0.1°c, il faut donc que je renseigne 10....

**Comment by maheus** [comment]
ok je ne regardais pas la même chose, moi je check la partie `variables` et non `parameters`
voici mes  valeurs ça parait plus cohérent, j'ai bien 1.5° C de variations , par contre j'ai 6 en value pour le 53 et non 1 
```
        {
          "id": 50,
          "value": 15
        },
        {
          "id": 53,
          "value": 6
        }
```
Si vous avez le temps de tester voir ce que ça donne chez vous.

**Comment by grigaux** [comment]
Bonjour,

Pour moi, les valeurs pour retrouver un fonctionnement normal est 10 pour les deux ID. Soit +1°c au-dessus de la consigne et -1°c en dessous de la consigne.
Merci


De : maheus ***@***.***>
Envoyé : mardi 12 décembre 2023 22:57
À : maheus/fumis_integration ***@***.***>
Cc : RIGAUX Guillaume ***@***.***>; Author ***@***.***>
Objet : Re: [maheus/fumis_integration] Problème avec le mode préréglage (Issue #13)


ok je ne regardais pas la même chose, moi je check la partie variables et non parameters
voici mes valeurs ça parait plus cohérent, j'ai bien 1.5° C de variations , par contre j'ai 6 en value pour le 53 et non 1

        {

          "id": 50,

          "value": 15

        },

        {

          "id": 53,

          "value": 6

        }

Si vous avez le temps de tester voir ce que ça donne chez vous.

**Comment by maheus** [comment]
ok merci
