### ISSUE TITLE
heta 200

### ISSUE THREAD

**Issue by doyoumind1** [maheus/fumis_integration#15]
Hi

I am complete newbie but I have been able to see and operate the pellet stove from HA. Thank you!
I have a Heta 200 and it has a tendency to switch on even if the target temperature is already below the current temperature. I guess this has something to do with the known issue. 

I've seen you provide a code (-curl...) address that, but I don't know where this have to be pasted. 

Can you help me on that? 
Thank you

**Comment by maheus** [comment]
Hi @doyoumind1 ,

I Don't understand your question, your  Heta 200 a tendency to switch on even if the target temperature is already below the current temperature but it switch on without Homeassistant or with homeassistant ?
If it start without Homeassistant you must contact your stove seller , if not so can you post your automation who start the stove please.

**Comment by maheus** [comment]
@doyoumind1 , this issue has no return sinde two weeks , i close it.
