### ISSUE TITLE
Question : History Feature

### ISSUE THREAD

**Issue by LoicC04** [maheus/fumis_integration#6]
Hi,
I'd like to get history of temperatures and data from the past day, week, month. I can see thet on the stove UI.
Is there any documentation of https://api.fumis.si/v1/ for endpoints other than /status ?

**Comment by maheus** [comment]
Hi Loic, there is no documentation :( .
For my history , i use the Homeassistant history functionnality

**Comment by LoicC04** [comment]
Ok, Thanks for the answer.
