### ISSUE TITLE
Modify the power

### ISSUE THREAD

**Issue by Bibouche** [maheus/fumis_integration#7]
Hey

Thanks for the code.
Is there a possibility to modify the power from 1 to 5?
Because on my stove only the power modifies the temperature

**Comment by maheus** [comment]
Hi @Bibouche , i'm sorry but i don't understand your issue . Do you can give me some more details please ?

**Comment by Bibouche** [comment]
On the PelletControl application or on home assistant with fumis, when I change the temperature, the stove does not react. The stove reacts only to powers 1 - 2 - 3 - 4 and 5.
The more the power increases, the more the stove heats up.
I would like to know if there is the possibility to change the power

**Comment by maheus** [comment]
ok, il see. my stove have a "auto power" and it changes automatically . Maybe your stove have not this functionality.
i'm not sure that a climate entity can doing this. 
do you can execute `curl` command and view the differences after you change the power

**Comment by maheus** [comment]
``` curl -H 'username:0016D00+++++' -H 'password:++++' https://api.fumis.si/v1/status/```

**Comment by Bibouche** [comment]
For information my stove is the Clou Pellet Compact.
I ran the command and here are the two results.
I specify that I changed the power via the PelletControl application because I cannot on Home assistant
On the first image the stove is in power 3 and on the second in power 1

**Comment by Bibouche** [comment]
![Power 3](https://user-images.githubusercontent.com/112384703/208303719-dfb02971-e9ba-4665-bc22-f3924401ecfd.png)

**Comment by Bibouche** [comment]
![Power 1](https://user-images.githubusercontent.com/112384703/208303729-9438e7b5-7f8f-484c-b356-a76629d9e230.png)

**Comment by maheus** [comment]
Hi @Bibouche , i'm sorry but i must have delete your pictures because your ID was in.

**Comment by Bibouche** [comment]
Ah darn .  Were you able to look at the images before deleting?

**Comment by maheus** [comment]
yes , test in progress

**Comment by maheus** [comment]
changes is ok, i commit tomorrow

**Comment by maheus** [comment]
acutal power ->
![image](https://user-images.githubusercontent.com/2638802/208325825-a90702c9-6f0e-4cb3-8544-f2311d84dcc3.png)
set new power via service ->
![image](https://user-images.githubusercontent.com/2638802/208325851-a9019e75-9f85-4a28-8c5e-b05ce29c8108.png)
new power ->
![image](https://user-images.githubusercontent.com/2638802/208326158-8802b2ee-bc19-4a85-9d5d-18c378749f43.png)

**Comment by maheus** [comment]
commit in branch refactor, please @Bibouche  do you can test it .

**Comment by Bibouche** [comment]
Thank you for the test . I can't call the service because I don't have the function : set_power_stove

**Comment by maheus** [comment]
you have get new code from refactor branch and restart homeassistant ?

**Comment by Bibouche** [comment]
Oh no, I didn't see. I remove the old integration and reinstall the new one with the new code and I test

**Comment by Bibouche** [comment]
Everything works ! It's perfect. I can now change the power.
Thank you very much for your time and help.
Now I will look to create a button to change the levels

**Comment by maheus** [comment]
yes it is easy , for example create an entry number and an automation who is triggering by a changement on the new entry number. the automation action will call the service set_power_stove with the `trigger.to_state.state` who contains the new value
