### ISSUE TITLE
Can't power on the stove

### ISSUE THREAD

**Issue by Crapoto94** [maheus/fumis_integration#9]
Hi, 
The integration is OK for me, bue i juste need to power on my stove with a switch or a button.
Is it possible ? How can i do it ?

**Comment by Crapoto94** [comment]
Bon, j'ai vu que tu étais Français, et ça m'arrange, je ne suis pas sur de mon Anglais.
J'explique mon problème.
Mon fils est handicapé, et en journée, il a l'application native pour le poêle.
Sauf que la nuit, il n'a pas son smartphone, donc je dois commander le poele autrement. Sachant qu'il n'y a pas de skill alexa pour le poele, je pensais le faire via HOME ASSISTANT.  Mais pour ça, il faut que je puisse le démarrer. 
Je lis bien les 5 sensor, mais je ne sais pas comment lui dire de démarrer le poele.

Merci de ton aide.

**Comment by maheus** [comment]
Hello,

Je suis en vacances mais je vais faire ce que je peux pour vous aider.
Vous avez plusieurs choix pour démarrer le poêle:
- soit via une automatisation et le service climate.turn_on/off
- soit via l'entité climate.(le nom de ton poêle)
- soit via un script 
Tout dépend selon quel critère vous souhaitez démarrer votre poêle

**Comment by maheus** [comment]
sans retour, je suppose que vous avez réussi à vous en sortir, je clos l'issue

**Comment by Crapoto94** [comment]
Pardon, je n'avais pas vu la réponse.
En fait non, cela ne fonctionne pas,  car je n'ai pas d'entité climate.(nom poele).
J'ai juste les sensor.
![image](https://github.com/maheus/fumis_integration/assets/88445989/f199c015-3842-4f2d-83cc-48058e965ec5)
![image](https://github.com/maheus/fumis_integration/assets/88445989/9f43520a-e3d1-430d-9b1d-f5dfc7a978d1)

**Comment by Crapoto94** [comment]
Voila mes logs
```
2023-08-16 16:28:34.795 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform fumis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: homeassistant.helpers.device_registry.DeviceRegistry.async_get_or_create() argument after ** must be a mapping, not list
2023-08-16 16:28:34.799 ERROR (MainThread) [homeassistant.components.climate] Error while setting up fumis platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Crapoto94** [comment]
(et mes sensor sont correctement lus)

**Comment by maheus** [comment]
ok donc il y a un problème lors de l'ajout du poêle.

**Comment by maheus** [comment]
le `after "**"` c'est ce qu'il y a dans les logs ou vous avez masqué quelque chose ?

**Comment by Crapoto94** [comment]
j'ai rien masqué

**Comment by maheus** [comment]
ok merci

**Comment by Crapoto94** [comment]
Tu veux un accès à mon HA ?

**Comment by Crapoto94** [comment]
Je crois qu'en ce moment ces serveurs FUMIS sont down, mais ils étaient UP quand j'ai fait mon intégration

**Comment by maheus** [comment]
je monte un HA de test pour voir si je reproduit

**Comment by maheus** [comment]
bon je confirme que les serveurs de fumis sont mort donc pour le moment je ne peux pas tester mais dès qu'ils reviennent je testerais

**Comment by maheus** [comment]
je constate l'erreur sans doute une modif sur la nouvelle version de HA que j'ai pas vu , je vais fix

**Comment by maheus** [comment]
Pouvez vous reinstaller le components avec mon dernier commit et restart HA svp . (il faut que je le refactor car il y a eu pas mal de change sur HA depuis que je l'ai mis en place)

**Comment by Crapoto94** [comment]
Bon, je pense que c'est OK, mais comme les serveurs de FUMIS son à nouveau DOWN...
en tous cas l'appareil est créé
je me suis fait une petite carte rapide

![image](https://github.com/maheus/fumis_integration/assets/88445989/4af9105d-a63f-42c4-8716-8bee924c5e24)

**Comment by maheus** [comment]
parfait, je vais faire un nouvelle version ce soir ou demain pour corrigé aussi 2 ou 3 choses que j'ai vu

**Comment by maheus** [comment]
nouvelle version dans la branche refactor:
https://github.com/maheus/fumis_integration/tree/refactor
